-- LM_USERS 테이블에 추가 필드 추가
-- 실행 전 백업을 권장합니다.

-- 이메일 필드 추가 (아이디/비밀번호 찾기용, 고유값)
ALTER TABLE LM_USERS ADD COLUMN EMAIL VARCHAR(255) NULL AFTER USERNAME;
ALTER TABLE LM_USERS ADD UNIQUE INDEX idx_email (EMAIL);

-- 생년월일 필드 추가
ALTER TABLE LM_USERS ADD COLUMN BIRTH_DATE DATE NULL AFTER EMAIL;

-- 성별 필드 추가 (M: 남성, F: 여성, O: 기타)
ALTER TABLE LM_USERS ADD COLUMN GENDER CHAR(1) NULL AFTER BIRTH_DATE;

-- 자기소개 필드 추가
ALTER TABLE LM_USERS ADD COLUMN BIO TEXT NULL AFTER GENDER;

-- 비밀번호 재설정 토큰 필드 추가
ALTER TABLE LM_USERS ADD COLUMN RESET_TOKEN VARCHAR(255) NULL;
ALTER TABLE LM_USERS ADD COLUMN RESET_TOKEN_EXPIRES DATETIME NULL;

-- 확인 쿼리
-- DESCRIBE LM_USERS;

